import html

def format_email_body(summary: str, patient_name: str = None, patient_id: str = None, include_metadata: bool = True):
    """
    Formats the email body for the doctor.
    Returns a tuple of (plain_text, html_content).
    """
    
    # Safe HTML escaping
    safe_summary = html.escape(summary).replace('\n', '<br>')
    safe_p_name = html.escape(patient_name) if patient_name else "N/A"
    safe_p_id = html.escape(patient_id) if patient_id else "N/A"

    # Plain text version
    text_parts = []
    if include_metadata:
        text_parts.append(f"Patient Name: {patient_name if patient_name else 'N/A'}")
        text_parts.append(f"Patient ID: {patient_id if patient_id else 'N/A'}")
        text_parts.append("-" * 20)
    
    text_parts.append("Summary Report:")
    text_parts.append(summary)
    
    plain_text = "\n".join(text_parts)

    # HTML version
    html_parts = []
    html_parts.append("<div style='font-family: Arial, sans-serif; color: #333;'>")
    
    if include_metadata:
        html_parts.append("<div style='background-color: #f4f4f4; padding: 10px; border-radius: 5px; margin-bottom: 20px;'>")
        html_parts.append(f"<p><strong>Patient Name:</strong> {safe_p_name}</p>")
        html_parts.append(f"<p><strong>Patient ID:</strong> {safe_p_id}</p>")
        html_parts.append("</div>")
    
    html_parts.append(f"<h3>Summary Report</h3>")
    html_parts.append(f"<div style='line-height: 1.5;'>{safe_summary}</div>")
    html_parts.append("<br><hr>")
    html_parts.append("<p style='font-size: 12px; color: #888;'>Generated by SpeakSpace Health Assistant</p>")
    html_parts.append("</div>")

    html_content = "\n".join(html_parts)

    return plain_text, html_content
